# Promise
Promiseには、非同期処理の結果をハンドリングするためのインスタンスメソッドが3つある(then, catch, finally)
## then()
- Promiseインスタンスがfulfilled or rejectedになった際に実行するコールバックを登録するメソッド
```javascript
const promise = new Promise()
promise.then(
  value => { // valueは解決済みPromiseインスタンスの値が入る
    // 成功時の処理
  },
  err => {
    // 失敗時の処理
  }
)
```
then()によるPromiseのチェーンで非同期処理実行を実装
then()で直前の非同期処理の結果を引数として、結果をPromiseで返す非同期関数の呼び出しを繰り返すことで、非同期処理の逐次処理を記述
```javascript
asyncFunc1(input)
  .then(asyncFunc2) // asyncFunc1完了後, その結果を引数にasyncFunc2を実行
  .then(asyncFunc3) // asyncFunc2完了後, その結果を引数にasyncFunc3を実行
  .then(asyncFunc4) // asyncFunc3完了後, その結果を引数にasyncFunc4を実行
  .then(result => {
    //全ての非同期処理が完了した後の処理
  })
  .catch(err => {
    // エラーハンドリング
  })
```
## catch()
then()はonFulfilled, onRejectedはどちらも省略可能だが、onFurfilledを省略する場合はthen()の代わりに`catch()`を使える
```javascript
// then()を2つの引数で実行するパターン
asyncFunc1(input)
  .then(
    asyncFunc2,
    err => {
      // asyncFunc1のエラーハンドリング
    }
  )
  .then(
    result => {
      // この中で発生したエラーは第二引数でハンドリングされない
    },
    err => {
      // asyncFunc2用のエラーハンドリング
    }
  )
// onRejectedを省略し、thenの後ろにcatchを用いるパターン

asyncFunc1(input)
  .then(asyncFunc2)
  .then(result => {}) // ここで発生したエラーもcatch()内でハンドリングされる
  .catch(
    err => {
      //エラーハンドリングをここに集約できる
    }
  )
```
## finally()
非同期処理が成功したかどうかに関わらず、Promiseインスタンスがsettled状態になった時実行されるコールバック関数

これらのメソッドに渡すコールバックはPromiseインスタンスの状態に関わらず、常に非同期的に実行される
```javascript
Promise.resolve('foo').then(result => console.log('コールバック', result))
console.log('この行が先に実行される')
```
## Promiseのスタティックメソッド
ショートサーキット: 引数の全てのPromiseインスタンスがsettledになるのを待たずに戻り値のPromiseインスタンスがsettledになることをショートサーキットという
**ショートサーキットの条件**
`Promise.all()`: 1つでもrejectedになったとき
`Promise.race()`: 1つでもsettledになったとき
`Promise.allSettled()`: ショートサーキットしない
`Promise.any()`: 1つでもfulfilledになった時
